-- Grants for hauling application user
GRANT USAGE ON SCHEMA hauling TO hauling;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hauling TO hauling;
ALTER DEFAULT PRIVILEGES IN SCHEMA hauling GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hauling;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA hauling TO hauling;
ALTER DEFAULT PRIVILEGES IN SCHEMA hauling GRANT USAGE ON SEQUENCES TO hauling;
